services:
  - type: web
    name: telegram-ytdl-bot
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true

    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_MAX_BYTES
        value: "1900000000"
      - key: CHAT_WHITELIST
        value: ""
